uv:
  mail:
    fromDisplayName: Urlaubsverwaltung
    replyToDisplayName: Urlaubsverwaltung

spring:
  web:
    resources:
      cache:
        cachecontrol:
          cache-public: true
          cache-private: true
          max-age: 365d
      chain:
        cache: true
        strategy:
          content:
            enabled: true
            paths: /css/**.css,/favicons/**,/images/**
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 10
  datasource:
    username: urlaubsverwaltung
    password: urlaubsverwaltung
    url: jdbc:postgresql://localhost:5434/urlaubsverwaltung
  jpa:
    open-in-view: false
  session:
    jdbc:
      initialize-schema: always
  messages:
    basename: messages,launchpad-core
    fallback-to-system-locale: false
  liquibase:
    change-log: classpath:/dbchangelogs/changelogmaster.xml
  thymeleaf:
    servlet:
      produce-partial-output-while-processing: false
  threads:
    virtual:
      enabled: true

server:
  compression:
    min-response-size: 1024
    enabled: true
  forward-headers-strategy: native
  tomcat:
    remoteip:
      port-header: X-Forwarded-Port
      protocol-header: X-Forwarded-Proto
springdoc:
  swagger-ui:
    disable-swagger-default-url: true

management:
  endpoint:
    prometheus:
      enabled: false
  endpoints:
    web:
      exposure:
        include: info, health

info:
  app:
    name: "@project.name@"
    version: "@project.version@"
